on:
  pull_request:
    types: [opened,reopened]
  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Run the install script
        run: bash scripts/install.sh